import {useEffect, useState} from 'react'

import Head from 'next/head'

import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';

import Navbar from '../components/Navbar'
import BooksTable from '../components/BooksTable'
import AuthorInfo from '../components/AuthorInfo'
import PopularAuthorsList from '../components/PopularAuthorsList';

import { getAuthor, getAuthorWorks } from '../utils/api/authors';
//bonus point
import CircularLoading from '../components/CircularProgress'


export default function Home() {
  const [authorKey, setAuthorKey] = useState("OL23919A")
  const [authorData, setAuthorData] = useState({})
  const [authorWorks, setAuthorWorks] = useState([])
  const [isLoading, setIsLoading] = useState(true);
  const [isbookLoading, setIsBookLoading] = useState(true);

  useEffect(()=> {
    setIsLoading(true);
    getAuthor(authorKey).then((data)=> {
      setAuthorData(data)
      setIsLoading(false)
    })
  }, [authorKey])

  useEffect(()=> {
    setIsBookLoading(true);
    getAuthorWorks(authorKey).then((data)=> {
      console.log(data)
      setAuthorWorks(data)
      setIsBookLoading(false);
    })
  }, [authorKey])

  return (
    <div>
      <Head>
        <title>Library App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <Container maxWidth="md">
          <Grid container spacing={4}>
            <Grid item xs={8}>
              <Box>
              {isLoading ? (
                  <CircularLoading text="author data loading..." />
                ) : (
                <AuthorInfo author={authorData} />
                )}
                 {isbookLoading ? (
                  <CircularLoading text="author book Loading..." />
                ) : (
                <BooksTable books={authorWorks} />
                )}
              </Box>
            </Grid>
            <Grid item xs={4}>
              <PopularAuthorsList setAuthorKey={setAuthorKey}/>
            </Grid>
          </Grid>
        </Container>
      </main>
    </div>
  )
}
